spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_division?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

